apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: public-oidc-discovery
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  path: components/public-oidc-discovery
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
